---
- name: Optimize Deployment
  hosts: all
  gather_facts: yes

  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
      async: 300
      poll: 0

    - name: Wait for nginx to be installed
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_results
      until: async_results.finished
      retries: 30
      delay: 10
      with_items:
        - "{{ ansible_job_ids }}"
      when: async_results.ansible_job_id is defined

    - name: Check if my_var is defined
      debug:
        msg: "The value of my_var is {{ my_var }}"
      when: my_var is defined

    - name: Fail if my_var is not defined
      fail:
        msg: "my_var is not defined!"
      when: my_var is not defined
 