---
- name: Deploying web server
  hosts: frontend
  become: yes
  roles:
    - webserver

- name: Deploying backend
  hosts: backend
  become: yes
  roles:
    - application

- name: Deploying web server
  hosts: database
  become: yes
  roles:
    - database